
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  resources:
    - url: /local/config-template-card.js
      type: module
    - url: /local/decluttering-card.js
      type: module
    - url: /local/card-mod.js
      type: module
    - type: css
      url: 'https://fonts.googleapis.com/css?family=Poppins'

# weather:
#   - platform: template
#     name: Weather
#     condition_template: '{{ states(''weather.my_region'') }}'
#     temperature_template: '{{ states(''input_number.temperature'') | float }}'
#     temperature_unit: °C
#     humidity_template: '{{ states(''input_number.humidity'') | float }}'
#     forecast_template: '{{ state_attr(''weather.my_region'', ''forecast'') }}'

climate:
  - platform: generic_thermostat
    name: radiator_bedroom
    heater: input_boolean.radiator_state_bedroom
    target_sensor: input_number.radiator_temperature_bedroom
    min_temp: 5
    max_temp: 25
    ac_mode: false
    hot_tolerance: 0.5
    cold_tolerance: 0.1
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 30
  - platform: generic_thermostat
    name: radiator_living_room
    heater: input_boolean.radiator_state_living_room
    target_sensor: input_number.radiator_temperature_living_room
    min_temp: 5
    max_temp: 25
    ac_mode: false
    hot_tolerance: 0.5
    cold_tolerance: 0.1
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 30
  - platform: generic_thermostat
    name: radiator_bathroom
    heater: input_boolean.radiator_state_bathroom
    target_sensor: input_number.radiator_temperature_bathroom
    min_temp: 5
    max_temp: 25
    ac_mode: false
    hot_tolerance: 0.5
    cold_tolerance: 0.1
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 30

fan:
  - platform: template
    fans:
      fan_bedroom:
        friendly_name: Fan bedroom
        value_template: '{{ states(''input_boolean.fan_state_bedroom'') }}'
        turn_on:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.fan_state_bedroom
        turn_off:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.fan_state_bedroom
        percentage_template: >
          {{ states('input_number.fan_percentage_bedroom') if
          is_state('input_boolean.fan_state_bedroom', 'on') else 0 }}
        speed_count: 6
        set_percentage:
          - service: 'input_boolean.turn_{{ ''on'' if percentage > 0 else ''off'' }}'
            target:
              entity_id: input_boolean.fan_state_bedroom
          - service: input_number.set_value
            target:
              entity_id: input_number.fan_percentage_bedroom
            data:
              value: '{{ percentage }}'
        preset_modes:
          - 'off'
          - low
          - medium
          - high
        preset_mode_template: |
          {% if is_state('input_boolean.fan_state_bedroom', 'on') %}
            {% if state_attr('input_number.fan_percentage_bedroom', 'value') == 100 %}
              high
            {% elif state_attr('input_number.fan_percentage_bedroom', 'value') == 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - service: input_number.set_value
            target:
              entity_id: input_number.fan_percentage_bedroom
            data:
              value: |-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}
      fan_living_room:
        friendly_name: Fan living room
        value_template: '{{ states(''input_boolean.fan_state_living_room'') }}'
        turn_on:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.fan_state_living_room
        turn_off:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.fan_state_living_room
        percentage_template: >
          {{ states('input_number.fan_percentage_living_room') if
          is_state('input_boolean.fan_state_living_room', 'on') else 0 }}
        speed_count: 6
        set_percentage:
          - service: 'input_boolean.turn_{{ ''on'' if percentage > 0 else ''off'' }}'
            target:
              entity_id: input_boolean.fan_state_living_room
          - service: input_number.set_value
            target:
              entity_id: input_number.fan_percentage_living_room
            data:
              value: '{{ percentage }}'
        preset_modes:
          - 'off'
          - low
          - medium
          - high
        preset_mode_template: |
          {% if is_state('input_boolean.fan_state_living_room', 'on') %}
            {% if state_attr('input_number.fan_percentage_living_room', 'value') == 100 %}
              high
            {% elif state_attr('input_number.fan_percentage_living_room', 'value') == 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - service: input_number.set_value
            target:
              entity_id: input_number.fan_percentage_living_room
            data:
              value: |-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}

light:
  - platform: group
    name: Kitchen Lights Group
    entities:
      - light.ceiling_light_table_kitchen
      - light.ceiling_light_kitchen_1
      - light.ceiling_light_kitchen_2
      - light.ceiling_light_kitchen_3
      - light.ceiling_light_kitchen_4
  - platform: group
    name: Hall Lights Group
    entities:
      - light.ceiling_light_hall_1
      - light.ceiling_light_hall_2
      - light.ceiling_light_hall_3
  - platform: group
    name: Living Room Lights Group
    entities:
      - light.ceiling_light_living_room_1
      - light.ceiling_light_living_room_2
      - light.ceiling_light_living_room_3
      - light.ceiling_light_living_room_4
      - light.ceiling_light_living_room_5
      - light.ceiling_light_living_room_6
      - light.ceiling_light_living_room_7
      - light.ceiling_light_living_room_8
  - platform: group
    name: Bedroom Lights Group
    entities:
      - light.ceiling_light_bedroom_1
      - light.ceiling_light_bedroom_2
      - light.ceiling_light_bedroom_3
      - light.ceiling_light_bedroom_4
  - platform: group
    name: Bathroom Lights Group
    entities:
      - light.ceiling_light_bathroom_1
      - light.ceiling_light_bathroom_2

dummy:
  - platform: switch
    entity_id: lock_door
    name: Lock door
  - platform: light
    entity_id: outdoor_lamp_door_1
    name: Outdoor lamp door 1
  - platform: light
    entity_id: ceiling_light_hall_1
    name: Ceiling light hall 1
  - platform: light
    entity_id: ceiling_light_hall_2
    name: Ceiling light hall 2
  - platform: light
    entity_id: ceiling_light_hall_3
    name: Ceiling light hall 3
  - platform: switch
    entity_id: coffee_maker_kitchen
    name: Coffee maker kitchen
  - platform: switch
    entity_id: kettle_kitchen
    name: Kettle kitchen
  - platform: light
    entity_id: ceiling_light_table_kitchen
    name: Ceiling light table kitchen
  - platform: light
    entity_id: led_strip_kitchen
    name: Led strip kitchen
  - platform: light
    entity_id: ceiling_light_kitchen_1
    name: Ceiling light kitchen 1
  - platform: light
    entity_id: ceiling_light_kitchen_2
    name: Ceiling light kitchen 2
  - platform: light
    entity_id: ceiling_light_kitchen_3
    name: Ceiling light kitchen 3
  - platform: light
    entity_id: ceiling_light_kitchen_4
    name: Ceiling light kitchen 4
  - platform: switch
    entity_id: watering_can_bedroom
    name: Watering can bedroom
  - platform: switch
    entity_id: tv_bedroom
    name: TV bedroom
  - platform: switch
    entity_id: player_bedroom
    name: Player bedroom
  - platform: cover
    entity_id: blinds_bedroom
    name: Blinds bedroom
  - platform: light
    entity_id: lamp_bedroom_1
    name: Lamp bedroom 1
  - platform: light
    entity_id: lamp_bedroom_2
    name: Lamp bedroom 2
  - platform: light
    entity_id: outdoor_lamp_bedroom_1
    name: Outdoor lamp bedroom 1
  - platform: light
    entity_id: outdoor_lamp_bedroom_2
    name: Outdoor lamp bedroom 2
  - platform: light
    entity_id: ceiling_light_bedroom_1
    name: Ceiling light bedroom 1
  - platform: light
    entity_id: ceiling_light_bedroom_2
    name: Ceiling light bedroom 2
  - platform: light
    entity_id: ceiling_light_bedroom_3
    name: Ceiling light bedroom 3
  - platform: light
    entity_id: ceiling_light_bedroom_4
    name: Ceiling light bedroom 4
  - platform: switch
    entity_id: watering_can_living_room
    name: Watering can living room
  - platform: switch
    entity_id: tv_living_room
    name: TV living room
  - platform: switch
    entity_id: player_living_room
    name: Player living room
  - platform: cover
    entity_id: blinds_living_room
    name: Blinds living room
  - platform: light
    entity_id: floor_lamp_living_room
    name: Floor lamp living room
  - platform: light
    entity_id: outdoor_lamp_living_room_1
    name: Outdoor lamp living room 1
  - platform: light
    entity_id: outdoor_lamp_living_room_2
    name: Outdoor lamp living room 2
  - platform: light
    entity_id: wall_lighbulb_living_room
    name: Wall lightbulb living room
  - platform: light
    entity_id: led_strip_living_room
    name: Led strip living room
  - platform: light
    entity_id: ceiling_light_living_room_1
    name: Ceiling light living room 1
  - platform: light
    entity_id: ceiling_light_living_room_2
    name: Ceiling light living room 2
  - platform: light
    entity_id: ceiling_light_living_room_3
    name: Ceiling light living room 3
  - platform: light
    entity_id: ceiling_light_living_room_4
    name: Ceiling light living room 4
  - platform: light
    entity_id: ceiling_light_living_room_5
    name: Ceiling light living room 5
  - platform: light
    entity_id: ceiling_light_living_room_6
    name: Ceiling light living room 6
  - platform: light
    entity_id: ceiling_light_living_room_7
    name: Ceiling light living room 7
  - platform: light
    entity_id: ceiling_light_living_room_8
    name: Ceiling light living room 8
  - platform: switch
    entity_id: washing_mashine_bathroom
    name: Washing mashine bathroom
  - platform: cover
    entity_id: blinds_bathroom
    name: Blinds bathroom
  - platform: light
    entity_id: outdoor_lamp_bathroom
    name: Outdoor lamp bathroom
  - platform: light
    entity_id: mirror_light_bathroom
    name: Mirror light bathroom
  - platform: light
    entity_id: ceiling_light_bathroom_1
    name: Ceiling light bathroom 1
  - platform: light
    entity_id: ceiling_light_bathroom_2
    name: Ceiling light bathroom 2
  - platform: switch
    entity_id: robot_vacuum
    name: Robot vacuum

input_select:
  show_all:
    name: Show all settings
    options:
      - Show
      - Do not show
    initial: Show

input_number:
  fan_percentage_bedroom:
    name: Fan percentage bedroom
    min: 0
    max: 100
  fan_percentage_living_room:
    name: Fan percentage living room
    min: 0
    max: 100
  temperature:
    name: Temperature
    min: -100
    max: 100
  humidity:
    name: Humidity
    min: 0
    max: 100
  radiator_temperature_bedroom:
    name: Radiator temperature bedroom
    min: 5
    max: 25
    step: 0.5
  radiator_temperature_living_room:
    name: Radiator temperature living room
    min: 5
    max: 25
    step: 0.5
  radiator_temperature_bathroom:
    name: Radiator temperature bathroom
    min: 5
    max: 25
    step: 0.5

input_boolean:
  fan_state_bedroom:
    name: Fan state bedroom
  fan_state_living_room:
    name: Fan state living room
  radiator_state_bedroom:
    name: Radiator state bedroom
  radiator_state_living_room:
    name: Radiator state living room
  radiator_state_bathroom:
    name: Radiator state bathroom
  cctv_door:
    name: CCTV door
  cctv_living_room:
    name: CCTV living room
