
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# dummy devices: custom_components -> mk-maddin/dummy-HA
# cover
# dummy:
#   - platform: cover
#     entity_id: my_cover1
#     name: My Dummy Cover
# light
# dummy:
#   - platform: light
#     entity_id: my_light1
#     name: My Dummy Light
# switch
# dummy:
#   - platform: switch
#     entity_id: my_switch1
#     name: My Dummy Switch

dummy:
# door
  # random
    - platform: switch
      entity_id: lock_door
      name: Lock door
  # lights
    - platform: light
      entity_id: outdoor_lamp_door_1
      name: Outdoor lamp door 1
# hall
  # lights
    - platform: light
      entity_id: ceiling_light_hall_1
      name: Ceiling light hall 1
    - platform: light
      entity_id: ceiling_light_hall_2
      name: Ceiling light hall 2
    - platform: light
      entity_id: ceiling_light_hall_3
      name: Ceiling light hall 3
# kitchen
  # random
    - platform: switch
      entity_id: coffee_maker_kitchen
      name: Coffee maker kitchen
    - platform: switch
      entity_id: kettle_kitchen
      name: Kettle kitchen
  # lights
    - platform: light
      entity_id: ceiling_light_table_kitchen
      name: Ceiling light table kitchen
    - platform: light
      entity_id: led_strip_kitchen
      name: Led strip kitchen
    - platform: light
      entity_id: ceiling_light_kitchen_1
      name: Ceiling light kitchen 1
    - platform: light
      entity_id: ceiling_light_kitchen_2
      name: Ceiling light kitchen 2
    - platform: light
      entity_id: ceiling_light_kitchen_3
      name: Ceiling light kitchen 3
    - platform: light
      entity_id: ceiling_light_kitchen_4
      name: Ceiling light kitchen 4
# bedroom
  # random
    - platform: switch
      entity_id: watering_can_bedroom
      name: Watering can bedroom
    - platform: switch
      entity_id: tv_bedroom
      name: TV bedroom
    - platform: switch
      entity_id: player_bedroom
      name: Player bedroom
  # blinds
    - platform: cover
      entity_id: blinds_bedroom
      name: Blinds bedroom
  # lights
    - platform: light
      entity_id: lamp_bedroom_1
      name: Lamp bedroom 1
    - platform: light
      entity_id: lamp_bedroom_2
      name: Lamp bedroom 2
    - platform: light
      entity_id: outdoor_lamp_bedroom_1
      name: Outdoor lamp bedroom 1
    - platform: light
      entity_id: outdoor_lamp_bedroom_2
      name: Outdoor lamp bedroom 2
    - platform: light
      entity_id: ceiling_light_bedroom_1
      name: Ceiling light bedroom 1
    - platform: light
      entity_id: ceiling_light_bedroom_2
      name: Ceiling light bedroom 2
    - platform: light
      entity_id: ceiling_light_bedroom_3
      name: Ceiling light bedroom 3
    - platform: light
      entity_id: ceiling_light_bedroom_4
      name: Ceiling light bedroom 4
# living room
  # random
    - platform: switch
      entity_id: watering_can_living_room
      name: Watering can living room
    - platform: switch
      entity_id: tv_living_room
      name: TV living room
    - platform: switch
      entity_id: player_living_room
      name: Player living room
  # blinds
    - platform: cover
      entity_id: blinds_living_room
      name: Blinds living room
  # lights
    - platform: light
      entity_id: floor_lamp_living_room
      name: Floor lamp living room
    - platform: light
      entity_id: outdoor_lamp_living_room_1
      name: Outdoor lamp living room 1
    - platform: light
      entity_id: outdoor_lamp_living_room_2
      name: Outdoor lamp living room 2
    - platform: light
      entity_id: wall_lighbulb_living_room
      name: Wall lightbulb living room
    - platform: light
      entity_id: led_strip_living_room
      name: Led strip living room
    - platform: light
      entity_id: ceiling_light_living_room_1
      name: Ceiling light living room 1
    - platform: light
      entity_id: ceiling_light_living_room_2
      name: Ceiling light living room 2
    - platform: light
      entity_id: ceiling_light_living_room_3
      name: Ceiling light living room 3
    - platform: light
      entity_id: ceiling_light_living_room_4
      name: Ceiling light living room 4
    - platform: light
      entity_id: ceiling_light_living_room_5
      name: Ceiling light living room 5
    - platform: light
      entity_id: ceiling_light_living_room_6
      name: Ceiling light living room 6
    - platform: light
      entity_id: ceiling_light_living_room_7
      name: Ceiling light living room 7
    - platform: light
      entity_id: ceiling_light_living_room_8
      name: Ceiling light living room 8
# bathroom
  # random
    - platform: switch
      entity_id: washing_mashine_bathroom
      name: Washing mashine bathroom
  # blinds
    - platform: cover
      entity_id: blinds_bathroom
      name: Blinds bathroom
  # lights
    - platform: light
      entity_id: outdoor_lamp_bathroom
      name: Outdoor lamp bathroom
    - platform: light
      entity_id: mirror_light_bathroom
      name: Mirror light bathroom
    - platform: light
      entity_id: ceiling_light_bathroom_1
      name: Ceiling light bathroom 1
    - platform: light
      entity_id: ceiling_light_bathroom_2
      name: Ceiling light bathroom 2
# random
    - platform: switch
      entity_id: robot_vacuum
      name: Robot vacuum

input_select:
    show_all:
        name: Show all settings
        options:
          - Show
          - Do not show
        initial: Show

input_boolean:
    alarm_state:
        name: Alarm State
        icon: mdi:alarm
    home_occupied:
        name: Home Occupied
        icon: mdi:home
    house_guests:
        name: Home Guests
        icon: mdi:person
    automation_status:
        name: automation_status
        icon: mdi:matrix

# # door
  # cctv
    cctv_door:
        name: CCTV door
# # bedroom
  # heat
    radiator_bedroom:
        name: Radiator bedroom
    fan_bedroom:
        name: Fan bedroom
# living room
  # cctv
    cctv_living_room:
        name: CCTV living room
  # heat
    radiator_living_room:
        name: Radiator living room
    fan_living_room:
        name: Fan living room
# # bathroom
  # heat
    radiator_bathroom:
        name: Radiator bathroom